-- MySQL Script generated by MySQL Workbench
-- 09/21/17 23:49:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema usf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usf` DEFAULT CHARACTER SET utf8 ;
USE `usf` ;

-- -----------------------------------------------------
-- Table `usf`.`acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`acciones` (
  `id_accion` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_accion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`alergias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`alergias` (
  `id_alergia` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_alergia`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`diagnosticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`diagnosticos` (
  `id_diagnostico` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_diagnostico`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`areas` (
  `id_area` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`departamentos` (
  `id_departamento` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`ciudades` (
  `id_ciudad` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `id_departamento` INT(11) NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  INDEX `fk_ciudades_departamentos1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_ciudades_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `usf`.`departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposdocumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposdocumentos` (
  `id_tipoDocumento` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoDocumento`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`pacientes` (
  `id_paciente` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nroDocumento` INT(11) NOT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaMuerte` DATE NULL DEFAULT NULL,
  `celular` INT(15) NULL DEFAULT NULL,
  `telefono` INT(15) NULL DEFAULT NULL,
  `id_area` INT(11) NOT NULL,
  `id_ciudad` INT(11) NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `id_tipoDocumento` INT(11) NOT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_pacientes_areas1_idx` (`id_area` ASC),
  INDEX `fk_pacientes_ciudades1_idx` (`id_ciudad` ASC),
  INDEX `fk_pacientes_tiposDocumentos1_idx` (`id_tipoDocumento` ASC),
  CONSTRAINT `fk_pacientes_areas1`
    FOREIGN KEY (`id_area`)
    REFERENCES `usf`.`areas` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_ciudades1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `usf`.`ciudades` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_tiposDocumentos1`
    FOREIGN KEY (`id_tipoDocumento`)
    REFERENCES `usf`.`tiposdocumentos` (`id_tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`especialidades` (
  `id_especialidad` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_especialidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`roles` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`personales` (
  `id_personal` INT(11) NOT NULL AUTO_INCREMENT,
  `nroDocumento` INT(11) NOT NULL,
  `nroRegistro` INT(30) NULL DEFAULT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` INT(20) NULL DEFAULT NULL,
  `celular` INT(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `contrasena` VARCHAR(45) NULL DEFAULT NULL,
  `id_rol` INT(11) NOT NULL,
  `id_especialidad` INT(11) NULL DEFAULT NULL,
  `habilitado` TINYINT(1) NULL DEFAULT '1',
  `id_tipoDocumento` INT(11) NOT NULL,
  PRIMARY KEY (`id_personal`),
  INDEX `fk_usuarios_roles1_idx` (`id_rol` ASC),
  INDEX `fk_usuarios_especialidades1_idx` (`id_especialidad` ASC),
  INDEX `fk_personales_tiposDocumentos1_idx` (`id_tipoDocumento` ASC),
  CONSTRAINT `fk_personales_tiposDocumentos1`
    FOREIGN KEY (`id_tipoDocumento`)
    REFERENCES `usf`.`tiposdocumentos` (`id_tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_especialidades1`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `usf`.`especialidades` (`id_especialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `usf`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`niveles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`niveles` (
  `id_nivel` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'esto es para registrar las urgencias.',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`preconsultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`preconsultas` (
  `id_preconsulta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `id_nivel` INT(11) NOT NULL,
  `id_personal` INT(11) NOT NULL,
  `id_paciente` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_preconsulta`),
  INDEX `fk_preconsultas_niveles1_idx` (`id_nivel` ASC),
  INDEX `fk_preconsultas_personales1_idx` (`id_personal` ASC),
  INDEX `fk_preconsultas_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_preconsultas_niveles1`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `usf`.`niveles` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preconsultas_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preconsultas_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`consultas` (
  `id_consulta` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `nuevoDiagnostico` TINYINT(1) NULL DEFAULT NULL,
  `vieneReferido` TINYINT(1) NULL DEFAULT NULL,
  `seRefiere` TINYINT(1) NULL DEFAULT NULL,
  `fechaProximaConsulta` DATE NULL DEFAULT NULL,
  `id_personal` INT(11) NOT NULL,
  `id_preconsulta` BIGINT(20) NOT NULL,
  `id_paciente` BIGINT(20) NOT NULL,
  `observacionDiagnostico` VARCHAR(100) NULL DEFAULT NULL,
  `id_diagnostico` INT(11) NOT NULL,
  PRIMARY KEY (`id_consulta`),
  INDEX `fk_consultas_personales1_idx` (`id_personal` ASC),
  INDEX `fk_consultas_preconsultas1_idx` (`id_preconsulta` ASC),
  INDEX `fk_consultas_pacientes1_idx` (`id_paciente` ASC),
  INDEX `fk_consultas_diagnosticos1_idx` (`id_diagnostico` ASC),
  CONSTRAINT `fk_consultas_diagnosticos1`
    FOREIGN KEY (`id_diagnostico`)
    REFERENCES `usf`.`diagnosticos` (`id_diagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_preconsultas1`
    FOREIGN KEY (`id_preconsulta`)
    REFERENCES `usf`.`preconsultas` (`id_preconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisissolicitados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisissolicitados` (
  `id_analisisSolicitado` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Todos los registros de esta tabla podrá ver la encargada/o del laboratorio, y así poder empezar a realizar los análisis solicitados por el medico.',
  `pendiente` TINYINT(1) NULL DEFAULT '1',
  `fecha` DATE NULL DEFAULT NULL,
  `id_consulta` INT(11) NOT NULL,
  PRIMARY KEY (`id_analisisSolicitado`),
  INDEX `fk_analisisSolicitados_consultas1_idx` (`id_consulta` ASC),
  CONSTRAINT `fk_analisisSolicitados_consultas1`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `usf`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisis` (
  `id_analisis` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `id_analisisSolicitado` INT(11) NOT NULL,
  `id_personal` INT(11) NOT NULL,
  PRIMARY KEY (`id_analisis`),
  INDEX `fk_analisis_analisisSolicitados1_idx` (`id_analisisSolicitado` ASC),
  INDEX `fk_analisis_personales1_idx` (`id_personal` ASC),
  CONSTRAINT `fk_analisis_analisisSolicitados1`
    FOREIGN KEY (`id_analisisSolicitado`)
    REFERENCES `usf`.`analisissolicitados` (`id_analisisSolicitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisis_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposanalisis` (
  `id_tipoAnalisis` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Los tipos de análisis pueden ser Orina, Hemograma etc.',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoAnalisis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisissolicitadostiposanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisissolicitadostiposanalisis` (
  `id_analisisSolicitadoTipoAnalisis` INT(11) NOT NULL AUTO_INCREMENT,
  `id_analisisSolicitado` INT(11) NOT NULL,
  `id_tipoAnalisis` INT(11) NOT NULL,
  PRIMARY KEY (`id_analisisSolicitadoTipoAnalisis`, `id_analisisSolicitado`, `id_tipoAnalisis`),
  INDEX `fk_analisisSolicitados_has_tiposAnalisis_tiposAnalisis1_idx` (`id_tipoAnalisis` ASC),
  INDEX `fk_analisisSolicitados_has_tiposAnalisis_analisisSolicitado_idx` (`id_analisisSolicitado` ASC),
  CONSTRAINT `fk_analisisSolicitados_has_tiposAnalisis_analisisSolicitados1`
    FOREIGN KEY (`id_analisisSolicitado`)
    REFERENCES `usf`.`analisissolicitados` (`id_analisisSolicitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisisSolicitados_has_tiposAnalisis_tiposAnalisis1`
    FOREIGN KEY (`id_tipoAnalisis`)
    REFERENCES `usf`.`tiposanalisis` (`id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisistiposanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisistiposanalisis` (
  `id_analisisTipoAnalisis` INT(11) NOT NULL AUTO_INCREMENT,
  `id_analisis` INT(11) NOT NULL,
  `id_tipoAnalisis` INT(11) NOT NULL,
  PRIMARY KEY (`id_analisisTipoAnalisis`, `id_analisis`, `id_tipoAnalisis`),
  INDEX `fk_analisis_has_tiposAnalisis_tiposAnalisis1_idx` (`id_tipoAnalisis` ASC),
  INDEX `fk_analisis_has_tiposAnalisis_analisis1_idx` (`id_analisis` ASC),
  CONSTRAINT `fk_analisis_has_tiposAnalisis_analisis1`
    FOREIGN KEY (`id_analisis`)
    REFERENCES `usf`.`analisis` (`id_analisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisis_has_tiposAnalisis_tiposAnalisis1`
    FOREIGN KEY (`id_tipoAnalisis`)
    REFERENCES `usf`.`tiposanalisis` (`id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposexamenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposexamenes` (
  `id_tipoExamen` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoExamen`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`unidadesanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`unidadesanalisis` (
  `id_unidadAnalisis` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidadAnalisis`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`parametrosanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`parametrosanalisis` (
  `id_parametroAnalisis` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Esta tabla es para registar el nombre, unidad y los rangos que describen el estado del resultado. \n\n     ejemplo: Colesterol, mg/dL, normal: 100, Alto: 160 a 189, Inferior: 70.',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `id_unidadAnalisis` INT(11) NULL DEFAULT NULL,
  `id_tipoExamen` INT(11) NOT NULL,
  PRIMARY KEY (`id_parametroAnalisis`),
  INDEX `fk_parametrosAnalisis_unidadesAnalisis1_idx` (`id_unidadAnalisis` ASC),
  INDEX `fk_parametrosAnalisis_tiposExamenes1_idx` (`id_tipoExamen` ASC),
  CONSTRAINT `fk_parametrosAnalisis_tiposExamenes1`
    FOREIGN KEY (`id_tipoExamen`)
    REFERENCES `usf`.`tiposexamenes` (`id_tipoExamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parametrosAnalisis_unidadesAnalisis1`
    FOREIGN KEY (`id_unidadAnalisis`)
    REFERENCES `usf`.`unidadesanalisis` (`id_unidadAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`referencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`referencias` (
  `id_referencia` INT(11) NOT NULL AUTO_INCREMENT,
  `diasMaximos` INT(11) NULL DEFAULT NULL,
  `mesesMaximos` INT(11) NULL DEFAULT NULL,
  `anosMaximos` INT(11) NULL DEFAULT NULL,
  `normal` DOUBLE NULL DEFAULT NULL,
  `superior` DOUBLE NULL DEFAULT NULL,
  `inferior` DOUBLE NULL DEFAULT NULL,
  `diasMinimos` INT(11) NULL DEFAULT NULL,
  `mesesMinimos` INT(11) NULL DEFAULT NULL,
  `anosMinimos` INT(11) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `id_parametroAnalisis` INT(11) NOT NULL,
  PRIMARY KEY (`id_referencia`),
  INDEX `fk_referencias_parametrosAnalisis1_idx` (`id_parametroAnalisis` ASC),
  CONSTRAINT `fk_referencias_parametrosAnalisis1`
    FOREIGN KEY (`id_parametroAnalisis`)
    REFERENCES `usf`.`parametrosanalisis` (`id_parametroAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisistiposanalisisreferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisistiposanalisisreferencias` (
  `id_analisisTipoAnalisisReferencia` INT(11) NOT NULL AUTO_INCREMENT,
  `id_analisisTipoAnalisis` INT(11) NOT NULL,
  `id_analisis` INT(11) NOT NULL,
  `id_tipoAnalisis` INT(11) NOT NULL,
  `id_referencia` INT(11) NOT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_analisisTipoAnalisisReferencia`, `id_analisisTipoAnalisis`, `id_analisis`, `id_tipoAnalisis`, `id_referencia`),
  INDEX `fk_analisisTiposAnalisis_has_referencias_referencias1_idx` (`id_referencia` ASC),
  INDEX `fk_analisisTiposAnalisis_has_referencias_analisisTiposAnali_idx` (`id_analisisTipoAnalisis` ASC, `id_analisis` ASC, `id_tipoAnalisis` ASC),
  CONSTRAINT `fk_analisisTiposAnalisis_has_referencias_analisisTiposAnalisis1`
    FOREIGN KEY (`id_analisisTipoAnalisis` , `id_analisis` , `id_tipoAnalisis`)
    REFERENCES `usf`.`analisistiposanalisis` (`id_analisisTipoAnalisis` , `id_analisis` , `id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisisTiposAnalisis_has_referencias_referencias1`
    FOREIGN KEY (`id_referencia`)
    REFERENCES `usf`.`referencias` (`id_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`citas` (
  `id_cita` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `start` TIME NULL DEFAULT NULL,
  `end` TIME NOT NULL,
  `pendiente` TINYINT(1) NULL DEFAULT '1',
  `id_personal` INT(11) NOT NULL,
  `allDay` TINYINT(1) NULL DEFAULT '0',
  `title` VARCHAR(90) NULL DEFAULT NULL,
  `id_preconsulta` BIGINT(20) NULL DEFAULT NULL,
  `id_paciente` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `fk_citas_personales1_idx` (`id_personal` ASC),
  INDEX `fk_citas_preconsultas1_idx` (`id_preconsulta` ASC),
  INDEX `fk_citas_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_citas_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_preconsultas1`
    FOREIGN KEY (`id_preconsulta`)
    REFERENCES `usf`.`preconsultas` (`id_preconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`distritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`distritos` (
  `id_distritos` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_distritos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`dosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`dosis` (
  `id_dosis` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_dosis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`regionessanitarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`regionessanitarias` (
  `id_regionSanitaria` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_regionSanitaria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`establecimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`establecimientos` (
  `id_establecimiento` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `codigo` INT(4) NULL DEFAULT NULL,
  `id_distritos` INT(11) NOT NULL,
  `id_regionSanitaria` INT(11) NOT NULL,
  PRIMARY KEY (`id_establecimiento`),
  INDEX `fk_establecimientos_distritos1_idx` (`id_distritos` ASC),
  INDEX `fk_establecimientos_regionesSanitarias1_idx` (`id_regionSanitaria` ASC),
  CONSTRAINT `fk_establecimientos_distritos1`
    FOREIGN KEY (`id_distritos`)
    REFERENCES `usf`.`distritos` (`id_distritos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_establecimientos_regionesSanitarias1`
    FOREIGN KEY (`id_regionSanitaria`)
    REFERENCES `usf`.`regionessanitarias` (`id_regionSanitaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`farmaceuticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`farmaceuticas` (
  `id_farmaceutica` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_farmaceutica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`nombresmedicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`nombresmedicamentos` (
  `id_nombreMedicamento` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `nombreGenerico` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_nombreMedicamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`presentaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`presentaciones` (
  `id_presentacion` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_presentacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposconsumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposconsumo` (
  `id_tipoConsumo` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoConsumo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`unidadesmedidasmedicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`unidadesmedidasmedicamentos` (
  `id_unidadMedidaMedicamento` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidadMedidaMedicamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentos` (
  `id_medicamento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_nombreMedicamento` INT(11) NOT NULL,
  `id_dosis` INT(11) NULL DEFAULT NULL,
  `stockMinimo` VARCHAR(45) NULL DEFAULT NULL,
  `id_tipoConsumo` INT(11) NOT NULL,
  `id_farmaceutica` INT(11) NOT NULL,
  `id_unidadMedidaMedicamento` INT(11) NULL DEFAULT NULL,
  `id_presentacion` INT(11) NOT NULL,
  `cantidadFarmaceutica` VARCHAR(45) NULL DEFAULT NULL COMMENT 'un ejemplo -> 30 Id_presentacion , Si son comprimidos.',
  PRIMARY KEY (`id_medicamento`),
  INDEX `fk_medicamentos_dosis1_idx` (`id_dosis` ASC),
  INDEX `fk_medicamentos_tiposConsumo1_idx` (`id_tipoConsumo` ASC),
  INDEX `fk_medicamentos_farmaceuticas1_idx` (`id_farmaceutica` ASC),
  INDEX `fk_medicamentos_nombresMedicamentos1_idx` (`id_nombreMedicamento` ASC),
  INDEX `fk_medicamentos_unidadesMedidasMedicamentos1_idx` (`id_unidadMedidaMedicamento` ASC),
  INDEX `fk_medicamentos_presentaciones1_idx` (`id_presentacion` ASC),
  CONSTRAINT `fk_medicamentos_dosis1`
    FOREIGN KEY (`id_dosis`)
    REFERENCES `usf`.`dosis` (`id_dosis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_farmaceuticas1`
    FOREIGN KEY (`id_farmaceutica`)
    REFERENCES `usf`.`farmaceuticas` (`id_farmaceutica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_nombresMedicamentos1`
    FOREIGN KEY (`id_nombreMedicamento`)
    REFERENCES `usf`.`nombresmedicamentos` (`id_nombreMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_presentaciones1`
    FOREIGN KEY (`id_presentacion`)
    REFERENCES `usf`.`presentaciones` (`id_presentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_tiposConsumo1`
    FOREIGN KEY (`id_tipoConsumo`)
    REFERENCES `usf`.`tiposconsumo` (`id_tipoConsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_unidadesMedidasMedicamentos1`
    FOREIGN KEY (`id_unidadMedidaMedicamento`)
    REFERENCES `usf`.`unidadesmedidasmedicamentos` (`id_unidadMedidaMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`proveedores` (
  `id_proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`lotesmedicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`lotesmedicamentos` (
  `id_loteMedicamento` INT(11) NOT NULL AUTO_INCREMENT,
  `numeroLote` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `fechaVencimiento` DATE NULL DEFAULT NULL,
  `cantidadRecibida` VARCHAR(45) NOT NULL,
  `id_medicamento` INT(11) NOT NULL,
  `id_proveedor` INT(11) NOT NULL,
  PRIMARY KEY (`id_loteMedicamento`),
  INDEX `fk_lotesMedicamentos_medicamentos1_idx` (`id_medicamento` ASC),
  INDEX `fk_lotesMedicamentos_proveedores1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_lotesMedicamentos_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lotesMedicamentos_proveedores1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `usf`.`proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentosacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentosacciones` (
  `id_medicamentoAccion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_medicamento` INT(11) NOT NULL,
  `id_accion` INT(11) NOT NULL,
  PRIMARY KEY (`id_medicamentoAccion`, `id_medicamento`, `id_accion`),
  INDEX `fk_medicamentos_has_acciones_acciones1_idx` (`id_accion` ASC),
  INDEX `fk_medicamentos_has_acciones_medicamentos1_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_medicamentos_has_acciones_acciones1`
    FOREIGN KEY (`id_accion`)
    REFERENCES `usf`.`acciones` (`id_accion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_has_acciones_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`principiosactivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`principiosactivos` (
  `id_principioActivo` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_principioActivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentosprincipiosactivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentosprincipiosactivos` (
  `id_medicamentoPrincipio` INT(11) NOT NULL AUTO_INCREMENT,
  `id_medicamento` INT(11) NOT NULL,
  `id_principioActivo` INT(11) NOT NULL,
  `primerValor` VARCHAR(45) NULL DEFAULT NULL,
  `segundoValor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_medicamentoPrincipio`, `id_medicamento`, `id_principioActivo`),
  INDEX `fk_medicamentos_has_principiosActivos_principiosActivos1_idx` (`id_principioActivo` ASC),
  INDEX `fk_medicamentos_has_principiosActivos_medicamentos1_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_medicamentos_has_principiosActivos_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_has_principiosActivos_principiosActivos1`
    FOREIGN KEY (`id_principioActivo`)
    REFERENCES `usf`.`principiosactivos` (`id_principioActivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`solicitudesfarmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`solicitudesfarmacia` (
  `id_solicitudFarmacia` INT(11) NOT NULL AUTO_INCREMENT,
  `pendiente` TINYINT(1) NULL DEFAULT '1',
  `id_consulta` INT(11) NOT NULL,
  PRIMARY KEY (`id_solicitudFarmacia`),
  INDEX `fk_solicitudesFarmacia_consultas1_idx` (`id_consulta` ASC),
  CONSTRAINT `fk_solicitudesFarmacia_consultas1`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `usf`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentossolicitudesfarmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentossolicitudesfarmacia` (
  `id_medicamentoSolicitud` INT(11) NOT NULL AUTO_INCREMENT,
  `id_medicamento` INT(11) NOT NULL,
  `id_solicitudFarmacia` INT(11) NOT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_medicamentoSolicitud`, `id_medicamento`, `id_solicitudFarmacia`),
  INDEX `fk_medicamentos_has_solicitudesFarmacia_solicitudesFarmacia_idx` (`id_solicitudFarmacia` ASC),
  INDEX `fk_medicamentos_has_solicitudesFarmacia_medicamentos1_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_medicamentos_has_solicitudesFarmacia_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_has_solicitudesFarmacia_solicitudesFarmacia1`
    FOREIGN KEY (`id_solicitudFarmacia`)
    REFERENCES `usf`.`solicitudesfarmacia` (`id_solicitudFarmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tratamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tratamientos` (
  `id_tratamiento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_consulta` INT(11) NOT NULL,
  PRIMARY KEY (`id_tratamiento`),
  INDEX `fk_tratamientos_consultas1_idx` (`id_consulta` ASC),
  CONSTRAINT `fk_tratamientos_consultas1`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `usf`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentostratamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentostratamientos` (
  `id_medicamentoTratamiento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_medicamento` INT(11) NOT NULL,
  `id_tratamiento` INT(11) NOT NULL,
  `fehcaInicio` DATE NULL DEFAULT NULL,
  `fechaFin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_medicamentoTratamiento`, `id_medicamento`, `id_tratamiento`),
  INDEX `fk_medicamentos_has_tratamientos_tratamientos1_idx` (`id_tratamiento` ASC),
  INDEX `fk_medicamentos_has_tratamientos_medicamentos1_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_medicamentos_has_tratamientos_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_has_tratamientos_tratamientos1`
    FOREIGN KEY (`id_tratamiento`)
    REFERENCES `usf`.`tratamientos` (`id_tratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`pacientesalergias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`pacientesalergias` (
  `id_pacienteAlergia` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_paciente` BIGINT(20) NOT NULL,
  `id_alergia` BIGINT(20) NOT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pacienteAlergia`, `id_paciente`, `id_alergia`),
  INDEX `fk_pacientes_has_alergias_alergias1_idx` (`id_alergia` ASC),
  INDEX `fk_pacientes_has_alergias_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_pacientes_has_alergias_alergias1`
    FOREIGN KEY (`id_alergia`)
    REFERENCES `usf`.`alergias` (`id_alergia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_has_alergias_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`unidadesparametropre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`unidadesparametropre` (
  `id_unidadParametroPre` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidadParametroPre`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`parametrospreconsulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`parametrospreconsulta` (
  `id_parametroPreconsulta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `valorNormal` VARCHAR(45) NULL DEFAULT NULL,
  `valorAlto` VARCHAR(45) NULL DEFAULT NULL,
  `valorBajo` VARCHAR(45) NULL DEFAULT NULL,
  `id_unidadParametroPre` INT(11) NOT NULL,
  PRIMARY KEY (`id_parametroPreconsulta`),
  INDEX `fk_parametrosPreconsulta_unidadesParametroPre1_idx` (`id_unidadParametroPre` ASC),
  CONSTRAINT `fk_parametrosPreconsulta_unidadesParametroPre1`
    FOREIGN KEY (`id_unidadParametroPre`)
    REFERENCES `usf`.`unidadesparametropre` (`id_unidadParametroPre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`preconsultasparametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`preconsultasparametros` (
  `id_preconsultaParametro` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_preconsulta` BIGINT(20) NOT NULL,
  `id_parametroPreconsulta` BIGINT(20) NOT NULL,
  `valor` INT(11) NULL DEFAULT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_preconsultaParametro`, `id_preconsulta`, `id_parametroPreconsulta`),
  INDEX `fk_preconsultas_has_parametrosPreconsulta_parametrosPrecons_idx` (`id_parametroPreconsulta` ASC),
  INDEX `fk_preconsultas_has_parametrosPreconsulta_preconsultas1_idx` (`id_preconsulta` ASC),
  CONSTRAINT `fk_preconsultas_has_parametrosPreconsulta_parametrosPreconsul1`
    FOREIGN KEY (`id_parametroPreconsulta`)
    REFERENCES `usf`.`parametrospreconsulta` (`id_parametroPreconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preconsultas_has_parametrosPreconsulta_preconsultas1`
    FOREIGN KEY (`id_preconsulta`)
    REFERENCES `usf`.`preconsultas` (`id_preconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`rolesmovimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`rolesmovimientos` (
  `id_rol` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaMovimiento` TIMESTAMP NULL DEFAULT NULL,
  `tipoMovimiento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`stockmedicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`stockmedicamentos` (
  `id_stockMedicamento` INT(11) NOT NULL AUTO_INCREMENT,
  `stockActual` VARCHAR(45) NULL DEFAULT NULL,
  `id_medicamento` INT(11) NOT NULL,
  PRIMARY KEY (`id_stockMedicamento`),
  INDEX `fk_stockMedicamentos_medicamentos1_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_stockMedicamentos_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposanalisisparametrosanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposanalisisparametrosanalisis` (
  `id_tipoAnalisisParametroAnalisis` INT(11) NOT NULL AUTO_INCREMENT,
  `id_tipoAnalisis` INT(11) NOT NULL,
  `id_parametroAnalisis` INT(11) NOT NULL,
  PRIMARY KEY (`id_tipoAnalisisParametroAnalisis`, `id_tipoAnalisis`, `id_parametroAnalisis`),
  INDEX `fk_tiposAnalisis_has_parametrosAnalisis_parametrosAnalisis1_idx` (`id_parametroAnalisis` ASC),
  INDEX `fk_tiposAnalisis_has_parametrosAnalisis_tiposAnalisis1_idx` (`id_tipoAnalisis` ASC),
  CONSTRAINT `fk_tiposAnalisis_has_parametrosAnalisis_parametrosAnalisis1`
    FOREIGN KEY (`id_parametroAnalisis`)
    REFERENCES `usf`.`parametrosanalisis` (`id_parametroAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tiposAnalisis_has_parametrosAnalisis_tiposAnalisis1`
    FOREIGN KEY (`id_tipoAnalisis`)
    REFERENCES `usf`.`tiposanalisis` (`id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
