-- MySQL Script generated by MySQL Workbench
-- 10/14/17 02:22:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema usf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usf
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `usf` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema usf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usf` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------
-- Table `usf`.`drogas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`drogas` (
  `id_drogas` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_drogas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usf`.`sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`sintomas` (
  `id_sintoma` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usf`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`areas` (
  `id_area` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`departamentos` (
  `id_departamento` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`ciudades` (
  `id_ciudad` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `id_departamento` INT(11) NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  INDEX `fk_ciudades_departamentos1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_ciudades_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `usf`.`departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposdocumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposdocumentos` (
  `id_tipoDocumento` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoDocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`pacientes` (
  `id_paciente` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nroDocumento` INT(11) NOT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaMuerte` DATE NULL DEFAULT NULL,
  `celular` INT(15) NULL DEFAULT NULL,
  `telefono` INT(15) NULL DEFAULT NULL,
  `id_area` INT(11) NOT NULL,
  `id_ciudad` INT(11) NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `id_tipoDocumento` INT(11) NOT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_pacientes_areas1_idx` (`id_area` ASC),
  INDEX `fk_pacientes_ciudades1_idx` (`id_ciudad` ASC),
  INDEX `fk_pacientes_tiposDocumentos1_idx` (`id_tipoDocumento` ASC),
  CONSTRAINT `fk_pacientes_areas1`
    FOREIGN KEY (`id_area`)
    REFERENCES `usf`.`areas` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_ciudades1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `usf`.`ciudades` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_tiposDocumentos1`
    FOREIGN KEY (`id_tipoDocumento`)
    REFERENCES `usf`.`tiposdocumentos` (`id_tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`especialidades` (
  `id_especialidad` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_especialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`roles` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`personales` (
  `id_personal` INT(11) NOT NULL AUTO_INCREMENT,
  `nroDocumento` INT(11) NOT NULL,
  `nroRegistro` INT(30) NULL DEFAULT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` INT(20) NULL DEFAULT NULL,
  `celular` INT(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `contrasena` VARCHAR(45) NULL DEFAULT NULL,
  `id_rol` INT(11) NOT NULL,
  `id_especialidad` INT(11) NULL DEFAULT NULL,
  `habilitado` TINYINT(1) NULL DEFAULT '1',
  `id_tipoDocumento` INT(11) NOT NULL,
  PRIMARY KEY (`id_personal`),
  INDEX `fk_usuarios_roles1_idx` (`id_rol` ASC),
  INDEX `fk_usuarios_especialidades1_idx` (`id_especialidad` ASC),
  INDEX `fk_personales_tiposDocumentos1_idx` (`id_tipoDocumento` ASC),
  CONSTRAINT `fk_personales_tiposDocumentos1`
    FOREIGN KEY (`id_tipoDocumento`)
    REFERENCES `usf`.`tiposdocumentos` (`id_tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_especialidades1`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `usf`.`especialidades` (`id_especialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `usf`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`niveles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`niveles` (
  `id_nivel` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'esto es para registrar las urgencias.',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`preconsultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`preconsultas` (
  `id_preconsulta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `id_nivel` INT(11) NOT NULL,
  `id_personal` INT(11) NOT NULL,
  `id_paciente` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_preconsulta`),
  INDEX `fk_preconsultas_niveles1_idx` (`id_nivel` ASC),
  INDEX `fk_preconsultas_personales1_idx` (`id_personal` ASC),
  INDEX `fk_preconsultas_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_preconsultas_niveles1`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `usf`.`niveles` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preconsultas_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preconsultas_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`consultas` (
  `id_consulta` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `nuevoDiagnostico` TINYINT(1) NULL DEFAULT NULL,
  `vieneReferido` TINYINT(1) NULL DEFAULT NULL,
  `seRefiere` TINYINT(1) NULL DEFAULT NULL,
  `fechaProximaConsulta` DATE NULL DEFAULT NULL,
  `id_personal` INT(11) NOT NULL,
  `id_preconsulta` BIGINT(20) NOT NULL,
  `id_paciente` BIGINT(20) NOT NULL,
  `observacionDiagnostico` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_consulta`),
  INDEX `fk_consultas_personales1_idx` (`id_personal` ASC),
  INDEX `fk_consultas_preconsultas1_idx` (`id_preconsulta` ASC),
  INDEX `fk_consultas_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_consultas_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_preconsultas1`
    FOREIGN KEY (`id_preconsulta`)
    REFERENCES `usf`.`preconsultas` (`id_preconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`consultasSintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`consultasSintomas` (
  `id_consultaSintoma` INT NOT NULL AUTO_INCREMENT,
  `id_sintoma` INT NOT NULL,
  `id_consulta` INT(11) NOT NULL,
  `observaciones` VARCHAR(50) NULL,
  PRIMARY KEY (`id_consultaSintoma`, `id_sintoma`, `id_consulta`),
  INDEX `fk_sintomas_has_consultas_consultas1_idx` (`id_consulta` ASC),
  INDEX `fk_sintomas_has_consultas_sintomas_idx` (`id_sintoma` ASC),
  CONSTRAINT `fk_sintomas_has_consultas_sintomas`
    FOREIGN KEY (`id_sintoma`)
    REFERENCES `usf`.`sintomas` (`id_sintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sintomas_has_consultas_consultas1`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `usf`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usf`.`medicamentosEntregados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentosEntregados` (
  `id_medicamentoEntregado` INT NOT NULL AUTO_INCREMENT,
  `id_personal` INT(11) NOT NULL,
  `id_paciente` BIGINT(20) NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id_medicamentoEntregado`),
  INDEX `fk_medicamentosEntregados_personales1_idx` (`id_personal` ASC),
  INDEX `fk_medicamentosEntregados_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_medicamentosEntregados_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentosEntregados_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usf`.`medicamentosEntregados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentosEntregados` (
  `id_medicamentoEntregado` INT NOT NULL AUTO_INCREMENT,
  `id_personal` INT(11) NOT NULL,
  `id_paciente` BIGINT(20) NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id_medicamentoEntregado`),
  INDEX `fk_medicamentosEntregados_personales1_idx` (`id_personal` ASC),
  INDEX `fk_medicamentosEntregados_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_medicamentosEntregados_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentosEntregados_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usf`.`alergias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`alergias` (
  `id_alergia` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_alergia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisissolicitados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisissolicitados` (
  `id_analisisSolicitado` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Todos los registros de esta tabla podrá ver la encargada/o del laboratorio, y así poder empezar a realizar los análisis solicitados por el medico.',
  `pendiente` TINYINT(1) NULL DEFAULT 1,
  `fechaArealizar` DATE NULL DEFAULT NULL,
  `id_consulta` INT(11) NOT NULL,
  `muestrasObtenidas` TINYINT(1) NULL DEFAULT 0,
  `hora` TIME NULL,
  PRIMARY KEY (`id_analisisSolicitado`),
  INDEX `fk_analisissolicitados_consultas1_idx` (`id_consulta` ASC),
  CONSTRAINT `fk_analisissolicitados_consultas1`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `usf`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisis` (
  `id_analisis` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `id_personal` INT(11) NOT NULL,
  `id_analisisSolicitado` INT(11) NOT NULL,
  PRIMARY KEY (`id_analisis`),
  INDEX `fk_analisis_personales1_idx` (`id_personal` ASC),
  INDEX `fk_analisis_analisissolicitados1_idx` (`id_analisisSolicitado` ASC),
  CONSTRAINT `fk_analisis_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisis_analisissolicitados1`
    FOREIGN KEY (`id_analisisSolicitado`)
    REFERENCES `usf`.`analisissolicitados` (`id_analisisSolicitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposanalisis` (
  `id_tipoAnalisis` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Los tipos de análisis pueden ser Orina, Hemograma etc.',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoAnalisis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisissolicitadostipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisissolicitadostipos` (
  `id_analisisSolicitadoTipo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_analisisSolicitado` INT(11) NOT NULL,
  `id_tipoAnalisis` INT(11) NOT NULL,
  PRIMARY KEY (`id_analisisSolicitadoTipo`, `id_analisisSolicitado`, `id_tipoAnalisis`),
  INDEX `fk_analisisSolicitados_has_tiposAnalisis_tiposAnalisis1_idx` (`id_tipoAnalisis` ASC),
  INDEX `fk_analisisSolicitados_has_tiposAnalisis_analisisSolicitado_idx` (`id_analisisSolicitado` ASC),
  CONSTRAINT `fk_analisisSolicitados_has_tiposAnalisis_analisisSolicitados1`
    FOREIGN KEY (`id_analisisSolicitado`)
    REFERENCES `usf`.`analisissolicitados` (`id_analisisSolicitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisisSolicitados_has_tiposAnalisis_tiposAnalisis1`
    FOREIGN KEY (`id_tipoAnalisis`)
    REFERENCES `usf`.`tiposanalisis` (`id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisisTipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisisTipos` (
  `id_analisisTipo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_analisis` INT(11) NOT NULL,
  `id_tipoAnalisis` INT(11) NOT NULL,
  PRIMARY KEY (`id_analisisTipo`, `id_analisis`, `id_tipoAnalisis`),
  INDEX `fk_analisis_has_tiposAnalisis_tiposAnalisis1_idx` (`id_tipoAnalisis` ASC),
  INDEX `fk_analisis_has_tiposAnalisis_analisis1_idx` (`id_analisis` ASC),
  CONSTRAINT `fk_analisis_has_tiposAnalisis_analisis1`
    FOREIGN KEY (`id_analisis`)
    REFERENCES `usf`.`analisis` (`id_analisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisis_has_tiposAnalisis_tiposAnalisis1`
    FOREIGN KEY (`id_tipoAnalisis`)
    REFERENCES `usf`.`tiposanalisis` (`id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposexamenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposexamenes` (
  `id_tipoExamen` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoExamen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`unidadesanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`unidadesanalisis` (
  `id_unidadAnalisis` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidadAnalisis`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`parametrosanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`parametrosanalisis` (
  `id_parametroAnalisis` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Esta tabla es para registar el nombre, unidad y los rangos que describen el estado del resultado. \n\n     ejemplo: Colesterol, mg/dL, normal: 100, Alto: 160 a 189, Inferior: 70.',
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `id_unidadAnalisis` INT(11) NULL DEFAULT NULL,
  `id_tipoExamen` INT(11) NOT NULL,
  PRIMARY KEY (`id_parametroAnalisis`),
  INDEX `fk_parametrosAnalisis_unidadesAnalisis1_idx` (`id_unidadAnalisis` ASC),
  INDEX `fk_parametrosAnalisis_tiposExamenes1_idx` (`id_tipoExamen` ASC),
  CONSTRAINT `fk_parametrosAnalisis_tiposExamenes1`
    FOREIGN KEY (`id_tipoExamen`)
    REFERENCES `usf`.`tiposexamenes` (`id_tipoExamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parametrosAnalisis_unidadesAnalisis1`
    FOREIGN KEY (`id_unidadAnalisis`)
    REFERENCES `usf`.`unidadesanalisis` (`id_unidadAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`referencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`referencias` (
  `id_referencia` INT(11) NOT NULL AUTO_INCREMENT,
  `diasMaximos` VARCHAR(45) NULL DEFAULT NULL,
  `mesesMaximos` VARCHAR(45) NULL DEFAULT NULL,
  `anosMaximos` VARCHAR(45) NULL DEFAULT NULL,
  `superior` VARCHAR(45) NULL DEFAULT NULL,
  `inferior` VARCHAR(45) NULL DEFAULT NULL,
  `diasMinimos` VARCHAR(45) NULL DEFAULT NULL,
  `mesesMinimos` VARCHAR(45) NULL DEFAULT NULL,
  `anosMinimos` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `id_parametroAnalisis` INT(11) NOT NULL,
  `general` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_referencia`),
  INDEX `fk_referencias_parametrosAnalisis1_idx` (`id_parametroAnalisis` ASC),
  CONSTRAINT `fk_referencias_parametrosAnalisis1`
    FOREIGN KEY (`id_parametroAnalisis`)
    REFERENCES `usf`.`parametrosanalisis` (`id_parametroAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisistiposanalisisreferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisistiposanalisisreferencias` (
  `id_analisisTipoAnalisisReferencia` INT(11) NOT NULL AUTO_INCREMENT,
  `id_analisisTipoAnalisis` INT(11) NOT NULL,
  `id_analisis` INT(11) NOT NULL,
  `id_tipoAnalisis` INT(11) NOT NULL,
  `id_referencia` INT(11) NOT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_analisisTipoAnalisisReferencia`, `id_analisisTipoAnalisis`, `id_analisis`, `id_tipoAnalisis`, `id_referencia`),
  INDEX `fk_analisisTiposAnalisis_has_referencias_referencias1_idx` (`id_referencia` ASC),
  INDEX `fk_analisisTiposAnalisis_has_referencias_analisisTiposAnali_idx` (`id_analisisTipoAnalisis` ASC, `id_analisis` ASC, `id_tipoAnalisis` ASC),
  CONSTRAINT `fk_analisisTiposAnalisis_has_referencias_analisisTiposAnalisis1`
    FOREIGN KEY (`id_analisisTipoAnalisis` , `id_analisis` , `id_tipoAnalisis`)
    REFERENCES `usf`.`analisisTipos` (`id_analisisTipo` , `id_analisis` , `id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisisTiposAnalisis_has_referencias_referencias1`
    FOREIGN KEY (`id_referencia`)
    REFERENCES `usf`.`referencias` (`id_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`citas` (
  `id_cita` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `start` TIME NULL DEFAULT NULL,
  `end` TIME NOT NULL,
  `pendiente` TINYINT(1) NULL DEFAULT '1',
  `id_personal` INT(11) NOT NULL,
  `allDay` TINYINT(1) NULL DEFAULT '0',
  `title` VARCHAR(90) NULL DEFAULT NULL,
  `id_preconsulta` BIGINT(20) NULL DEFAULT NULL,
  `id_paciente` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `fk_citas_personales1_idx` (`id_personal` ASC),
  INDEX `fk_citas_preconsultas1_idx` (`id_preconsulta` ASC),
  INDEX `fk_citas_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_citas_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_personales1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `usf`.`personales` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_preconsultas1`
    FOREIGN KEY (`id_preconsulta`)
    REFERENCES `usf`.`preconsultas` (`id_preconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`diagnosticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`diagnosticos` (
  `id_diagnostico` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_diagnostico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`farmaceuticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`farmaceuticas` (
  `id_farmaceutica` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_farmaceutica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentos` (
  `id_medicamento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_farmaceutica` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`id_medicamento`),
  INDEX `fk_medicamentos_farmaceuticas1_idx` (`id_farmaceutica` ASC),
  CONSTRAINT `fk_medicamentos_farmaceuticas1`
    FOREIGN KEY (`id_farmaceutica`)
    REFERENCES `usf`.`farmaceuticas` (`id_farmaceutica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`pacientesalergias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`pacientesalergias` (
  `id_pacienteAlergia` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_paciente` BIGINT(20) NOT NULL,
  `id_alergia` BIGINT(20) NOT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pacienteAlergia`, `id_paciente`, `id_alergia`),
  INDEX `fk_pacientes_has_alergias_alergias1_idx` (`id_alergia` ASC),
  INDEX `fk_pacientes_has_alergias_pacientes1_idx` (`id_paciente` ASC),
  CONSTRAINT `fk_pacientes_has_alergias_alergias1`
    FOREIGN KEY (`id_alergia`)
    REFERENCES `usf`.`alergias` (`id_alergia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_has_alergias_pacientes1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `usf`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`unidadesparametropre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`unidadesparametropre` (
  `id_unidadParametroPre` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidadParametroPre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`parametrospreconsulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`parametrospreconsulta` (
  `id_parametroPreconsulta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `valorNormal` VARCHAR(45) NULL DEFAULT NULL,
  `valorAlto` VARCHAR(45) NULL DEFAULT NULL,
  `valorBajo` VARCHAR(45) NULL DEFAULT NULL,
  `id_unidadParametroPre` INT(11) NOT NULL,
  PRIMARY KEY (`id_parametroPreconsulta`),
  INDEX `fk_parametrosPreconsulta_unidadesParametroPre1_idx` (`id_unidadParametroPre` ASC),
  CONSTRAINT `fk_parametrosPreconsulta_unidadesParametroPre1`
    FOREIGN KEY (`id_unidadParametroPre`)
    REFERENCES `usf`.`unidadesparametropre` (`id_unidadParametroPre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`preconsultasparametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`preconsultasparametros` (
  `id_preconsultaParametro` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_preconsulta` BIGINT(20) NOT NULL,
  `id_parametroPreconsulta` BIGINT(20) NOT NULL,
  `valor` INT(11) NULL DEFAULT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_preconsultaParametro`, `id_preconsulta`, `id_parametroPreconsulta`),
  INDEX `fk_preconsultas_has_parametrosPreconsulta_parametrosPrecons_idx` (`id_parametroPreconsulta` ASC),
  INDEX `fk_preconsultas_has_parametrosPreconsulta_preconsultas1_idx` (`id_preconsulta` ASC),
  CONSTRAINT `fk_preconsultas_has_parametrosPreconsulta_parametrosPreconsul1`
    FOREIGN KEY (`id_parametroPreconsulta`)
    REFERENCES `usf`.`parametrospreconsulta` (`id_parametroPreconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preconsultas_has_parametrosPreconsulta_preconsultas1`
    FOREIGN KEY (`id_preconsulta`)
    REFERENCES `usf`.`preconsultas` (`id_preconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`tiposAnalisisParametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`tiposAnalisisParametros` (
  `id_tipoAnalisisParametro` INT(11) NOT NULL AUTO_INCREMENT,
  `id_tipoAnalisis` INT(11) NOT NULL,
  `id_parametroAnalisis` INT(11) NOT NULL,
  PRIMARY KEY (`id_tipoAnalisisParametro`, `id_tipoAnalisis`, `id_parametroAnalisis`),
  INDEX `fk_tiposAnalisis_has_parametrosAnalisis_parametrosAnalisis1_idx` (`id_parametroAnalisis` ASC),
  INDEX `fk_tiposAnalisis_has_parametrosAnalisis_tiposAnalisis1_idx` (`id_tipoAnalisis` ASC),
  CONSTRAINT `fk_tiposAnalisis_has_parametrosAnalisis_parametrosAnalisis1`
    FOREIGN KEY (`id_parametroAnalisis`)
    REFERENCES `usf`.`parametrosanalisis` (`id_parametroAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tiposAnalisis_has_parametrosAnalisis_tiposAnalisis1`
    FOREIGN KEY (`id_tipoAnalisis`)
    REFERENCES `usf`.`tiposanalisis` (`id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentosDrogas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentosDrogas` (
  `id_medicamentoDroga` INT NOT NULL AUTO_INCREMENT,
  `id_medicamento` INT(11) NOT NULL,
  `id_drogas` INT NOT NULL,
  `descripcionProporcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_medicamentoDroga`, `id_medicamento`, `id_drogas`),
  INDEX `fk_medicamentos_has_drogas_drogas1_idx` (`id_drogas` ASC),
  INDEX `fk_medicamentos_has_drogas_medicamentos1_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_medicamentos_has_drogas_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_has_drogas_drogas1`
    FOREIGN KEY (`id_drogas`)
    REFERENCES `usf`.`drogas` (`id_drogas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`analisisTiposReferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`analisisTiposReferencias` (
  `id_analisisTipoReferencia` INT NOT NULL AUTO_INCREMENT,
  `id_analisisTipo` INT(11) NOT NULL,
  `id_analisis` INT(11) NOT NULL,
  `id_tipoAnalisis` INT(11) NOT NULL,
  `id_referencia` INT(11) NOT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_analisisTipoReferencia`, `id_analisisTipo`, `id_analisis`, `id_tipoAnalisis`, `id_referencia`),
  INDEX `fk_analisisTipos_has_referencias_referencias1_idx` (`id_referencia` ASC),
  INDEX `fk_analisisTipos_has_referencias_analisisTipos1_idx` (`id_analisisTipo` ASC, `id_analisis` ASC, `id_tipoAnalisis` ASC),
  CONSTRAINT `fk_analisisTipos_has_referencias_analisisTipos1`
    FOREIGN KEY (`id_analisisTipo` , `id_analisis` , `id_tipoAnalisis`)
    REFERENCES `usf`.`analisisTipos` (`id_analisisTipo` , `id_analisis` , `id_tipoAnalisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analisisTipos_has_referencias_referencias1`
    FOREIGN KEY (`id_referencia`)
    REFERENCES `usf`.`referencias` (`id_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`consultasDiagnosticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`consultasDiagnosticos` (
  `id_consultaDiagnostico` INT NOT NULL AUTO_INCREMENT,
  `id_consulta` INT(11) NOT NULL,
  `id_diagnostico` INT(11) NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`id_consultaDiagnostico`, `id_consulta`, `id_diagnostico`),
  INDEX `fk_consultas_has_diagnosticos_diagnosticos1_idx` (`id_diagnostico` ASC),
  INDEX `fk_consultas_has_diagnosticos_consultas1_idx` (`id_consulta` ASC),
  CONSTRAINT `fk_consultas_has_diagnosticos_consultas1`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `usf`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_has_diagnosticos_diagnosticos1`
    FOREIGN KEY (`id_diagnostico`)
    REFERENCES `usf`.`diagnosticos` (`id_diagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentosXentregados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentosXentregados` (
  `id_medicamentoXentregado` INT NOT NULL AUTO_INCREMENT,
  `id_medicamento` INT(11) NOT NULL,
  `id_medicamentoEntregado` INT NOT NULL,
  `lote` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_medicamentoXentregado`, `id_medicamento`, `id_medicamentoEntregado`),
  INDEX `fk_medicamentos_has_medicamentosEntregados_medicamentosEntr_idx` (`id_medicamentoEntregado` ASC),
  INDEX `fk_medicamentos_has_medicamentosEntregados_medicamentos1_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_medicamentos_has_medicamentosEntregados_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_has_medicamentosEntregados_medicamentosEntreg1`
    FOREIGN KEY (`id_medicamentoEntregado`)
    REFERENCES `usf`.`medicamentosEntregados` (`id_medicamentoEntregado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `usf`.`medicamentosConsultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`medicamentosConsultas` (
  `id_medicamentoConsulta` INT NOT NULL AUTO_INCREMENT,
  `id_consulta` INT(11) NOT NULL,
  `id_medicamento` INT(11) NOT NULL,
  `medicamentoNoExistente` VARCHAR(45) NULL,
  `cantidadConsumo` VARCHAR(45) NULL COMMENT 'ejemplo 1 comp,  7.5 ml,  3 disparos. ',
  `cantidadTiempo` VARCHAR(45) NULL COMMENT 'ejemplo, cada 4 horas,  cada 8 horas.',
  `duracionConsumo` VARCHAR(45) NULL COMMENT 'por 15 días, por 2 meses.',
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`id_medicamentoConsulta`, `id_consulta`, `id_medicamento`),
  INDEX `fk_medicamentosTratamientos_consultas1_idx` (`id_consulta` ASC),
  INDEX `fk_medicamentosTratamientos_medicamentos1_idx` (`id_medicamento` ASC),
  CONSTRAINT `fk_medicamentosTratamientos_consultas1`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `usf`.`consultas` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentosTratamientos_medicamentos1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `usf`.`medicamentos` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
