-- MySQL Script generated by MySQL Workbench
-- 08/05/17 16:07:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema usf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usf` DEFAULT CHARACTER SET utf8 ;
USE `usf` ;

-- -----------------------------------------------------
-- Table `usf`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`pacientes` (
  `id_pacientes` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pacientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usf`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`especialidades` (
  `id_especialidades` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_especialidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usf`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`citas` (
  `id_citas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `hora` TIME NULL,
  `id_pacientes` INT NOT NULL,
  `id_especialidades` INT NOT NULL,
  PRIMARY KEY (`id_citas`),
  INDEX `fk_citas_pacientes_idx` (`id_pacientes` ASC),
  INDEX `fk_citas_especialidades1_idx` (`id_especialidades` ASC),
  CONSTRAINT `fk_citas_pacientes`
    FOREIGN KEY (`id_pacientes`)
    REFERENCES `usf`.`pacientes` (`id_pacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_especialidades1`
    FOREIGN KEY (`id_especialidades`)
    REFERENCES `usf`.`especialidades` (`id_especialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usf`.`citasMovimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usf`.`citasMovimientos` (
  `id_citas` INT NULL,
  `fecha` DATETIME NULL,
  `hora` TIME NULL,
  `id_pacientes` INT NULL,
  `id_especialidades` INT NULL,
  `fechaMovimiento` TIMESTAMP NULL,
  `tipoMovimiento` VARCHAR(45) NULL)
ENGINE = InnoDB;

USE `usf`;

DELIMITER $$
USE `usf`$$
CREATE DEFINER = CURRENT_USER TRIGGER `usf`.`citas_AFTER_UPDATE` AFTER UPDATE ON `citas` FOR EACH ROW
BEGIN
	INSERT INTO citasmovimientos(id_citas, fecha, hora, id_pacientes, id_especialidades, fechaMovimiento, tipoMovimiento) 
    VALUES (new.id_citas, new.fecha, new.hora, new.id_pacientes, new.id_especialidades, now(), 'actualización');
END$$

USE `usf`$$
CREATE DEFINER = CURRENT_USER TRIGGER `usf`.`citas_AFTER_DELETE` AFTER DELETE ON `citas` FOR EACH ROW
BEGIN
	INSERT INTO citasmovimientos(id_citas, fecha, hora, id_pacientes, id_especialidades, fechaMovimiento, tipoMovimiento) 
    VALUES (old.id_citas, old.fecha, old.hora, old.id_pacientes, old.id_especialidades, now(), 'eliminación');
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
