// FIND.
export const LISTAR_MEDICAMENTOS_TRATAMIENTOS_REQUEST = 'listar_medicamentos_tratamientos_request'
export const LISTAR_MEDICAMENTOS_TRATAMIENTOS_EXITO = 'listar_medicamentos_tratamientos_exito'
export const LISTAR_MEDICAMENTOS_TRATAMIENTOS_FALLO = 'listar_medicamentos_tratamientos_fallo'

// EDIT.
export const ABRIR_FORMULARIO_EDITAR_MEDICAMENTO_TRATAMIENTO_REQUEST = 'abrir_formulario_editar_medicamento_tratamiento_request'
export const ABRIR_FORMULARIO_EDITAR_MEDICAMENTO_TRATAMIENTO_EXITO = 'abrir_formulario_editar_medicamento_tratamiento_exito'
export const ABRIR_FORMULARIO_EDITAR_MEDICAMENTO_TRATAMIENTO_FALLO = 'abrir_formulario_editar_medicamento_tratamiento_fallo'

	export const EDITAR_MEDICAMENTO_TRATAMIENTO_REQUEST = 'edit_medicamento_tratamiento_request'
	export const EDITAR_MEDICAMENTO_TRATAMIENTO_EXITO = 'edit_medicamento_tratamiento_exito'
	export const EDITAR_MEDICAMENTO_TRATAMIENTO_FALLO = 'edit_medicamento_tratamiento_fallo'

// CREATE.
export const ABRIR_FORMULARIO_CREAR_MEDICAMENTO_TRATAMIENTO = 'abrir_formulario_crear_medicamento_tratamiento'

	export const CREAR_MEDICAMENTO_TRATAMIENTO_REQUEST = 'crear_medicamento_tratamiento_request'
	export const CREAR_MEDICAMENTO_TRATAMIENTO_EXITO = 'crear_medicamento_tratamiento_exito'
	export const CREAR_MEDICAMENTO_TRATAMIENTO_FALLO = 'crear_medicamento_tratamiento_fallo'

export const CERRAR_FORMULARIO_MEDICAMENTO_TRATAMIENTO = 'cerrar_formulario_medicamento_tratamiento'

// SHOW.
export const MOSTRAR_MEDICAMENTO_TRATAMIENTO_REQUEST = 'mostrar_medicamento_tratamiento_request'
export const MOSTRAR_MEDICAMENTO_TRATAMIENTO_EXITO = 'mostrar_medicamento_tratamiento_exito'
export const MOSTRAR_MEDICAMENTO_TRATAMIENTO_FALLO = 'mostrar_medicamento_tratamiento_fallo'

export const CERRAR_MODAL_MOSTRAR_MEDICAMENTO_TRATAMIENTO = 'cerrar_modal_mostrar_medicamento_tratamiento'

// DELETE.
export const ELIMINAR_MEDICAMENTO_TRATAMIENTO_REQUEST = 'eliminar_medicamento_tratamiento_request'
export const ELIMINAR_MEDICAMENTO_TRATAMIENTO_EXITO = 'eliminar_medicamento_tratamiento_exito'
export const ELIMINAR_MEDICAMENTO_TRATAMIENTO_FALLO = 'eliminar_medicamento_tratamiento_fallo'


